///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace プロジェクトC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the プロジェクトCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2160b28d-f87a-47a0-9498-94013a3c4af8")]
    public partial class プロジェクトCRepository : RepoGenBaseFolder
    {
        static プロジェクトCRepository instance = new プロジェクトCRepository();

        /// <summary>
        /// Gets the singleton class instance representing the プロジェクトCRepository element repository.
        /// </summary>
        [RepositoryFolder("2160b28d-f87a-47a0-9498-94013a3c4af8")]
        public static プロジェクトCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public プロジェクトCRepository() 
            : base("プロジェクトCRepository", "/", null, 0, false, "2160b28d-f87a-47a0-9498-94013a3c4af8", ".\\RepositoryImages\\プロジェクトCRepository2160b28d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2160b28d-f87a-47a0-9498-94013a3c4af8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class プロジェクトCRepositoryFolders
    {
    }
#pragma warning restore 0436
}
