///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace プロジェクトB
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the プロジェクトBRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b4c6f002-f26f-45c0-b006-7c9fee476451")]
    public partial class プロジェクトBRepository : RepoGenBaseFolder
    {
        static プロジェクトBRepository instance = new プロジェクトBRepository();

        /// <summary>
        /// Gets the singleton class instance representing the プロジェクトBRepository element repository.
        /// </summary>
        [RepositoryFolder("b4c6f002-f26f-45c0-b006-7c9fee476451")]
        public static プロジェクトBRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public プロジェクトBRepository() 
            : base("プロジェクトBRepository", "/", null, 0, false, "b4c6f002-f26f-45c0-b006-7c9fee476451", ".\\RepositoryImages\\プロジェクトBRepositoryb4c6f002.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b4c6f002-f26f-45c0-b006-7c9fee476451")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class プロジェクトBRepositoryFolders
    {
    }
#pragma warning restore 0436
}
