///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace プロジェクトA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the プロジェクトARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e7bb9fa1-4437-4d8f-ac9a-9d8f93263114")]
    public partial class プロジェクトARepository : RepoGenBaseFolder
    {
        static プロジェクトARepository instance = new プロジェクトARepository();

        /// <summary>
        /// Gets the singleton class instance representing the プロジェクトARepository element repository.
        /// </summary>
        [RepositoryFolder("e7bb9fa1-4437-4d8f-ac9a-9d8f93263114")]
        public static プロジェクトARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public プロジェクトARepository() 
            : base("プロジェクトARepository", "/", null, 0, false, "e7bb9fa1-4437-4d8f-ac9a-9d8f93263114", ".\\RepositoryImages\\プロジェクトARepositorye7bb9fa1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e7bb9fa1-4437-4d8f-ac9a-9d8f93263114")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class プロジェクトARepositoryFolders
    {
    }
#pragma warning restore 0436
}
